const events = [
  {
    id: 1,
    name: "Log Off Night 2024",
    date: " July 7 2024 ",
    dateDetails: "7th July 2024",
    time: "7:00pm - 11:00pm (GMT+8)",
    venue: "Bayview Hotel, George Town, Penang",
    session: "2023/2024",
    description: "An annual dinner to celebrate and appreciate final year computer science students' contributions.",
    details: "Log Off Night is the epic celebration marking the end of the 2023/2024 academic year for all Computer Science students! It’s a night where we come together to celebrate our achievements, honor our graduating final-year studets and bid farewell to dear friends.",
    tag1: "USM Students",
    tag2: "Prom Night",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/lon-2024-poster.webp"
  },
  {
    id: 2,
    name: "Project Innovation & eXploration in CS Education and Learning 2024",
    date: " July 2 2024 ",
    dateDetails: "2th June 2024",
    time: "10:00am - 12:40pm (GMT+8)",
    venue: "Dewan Budaya, USM",
    session: "2023/2024",
    description: "An annual flagship exhibition programme specially curated for final year computer science students.",
    details: "Project Innovation & eXploration in CS Education and Learning (PIXEL 2024) is a recognised annual flagship programme designed for final-year students, meticulously organised by the Computer Science Society in collaboration with the School of Computer Sciences, Universiti Sains Malaysia. As an extension of the Final Year Project (FYP) assessment, PIXEL 2024 allows students to display their work and gain valuable feedback from industry professionals. \nThis year, PIXEL returns with a broader range of distinguished honours and significant rewards, all targeted at accomplishing key milestones and encouraging academic achievement. PIXEL 2024 will implement a hybrid approach, with a virtual FYP exhibition and project evaluation followed by an Awards & Closing Ceremony being held at Dewan Budaya. \nLearn more about PIXEL 2024 at our official website!",
    tag1: "Year 4",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/pixel-2024-poster.webp"
  },
  {
    id: 3,
    name: "Annual General Meeting 2024",
    date: " June 26 2024 ",
    dateDetails: "26th June 2024",
    time: "7:50pm - 10:45pm (GMT+8)",
    venue: "Online",
    session: "2023/2024",
    description: "An annual event to showcase the achievements of CS Society throughout the year and elect the new executives members.",
    details: "The Annual General Meeting (AGM) is an annual event of CS Society aimed to showcase the achievements of the CS Society throughout the academic year and election is done to elect the new Executive Members for the next academic session. \nThe annual activity report showcases the events that CS Society has organised throughout the academic session. Get a glimpse of the behind-the-scenes action, the dedication and the hard work put in by the committees. \nThe CS Society Board Election is your chance to make your voice heard and vote for the new Top Committee members of CS Society, who will shoulder the responsibilities of leading the student body toward greater heights.",
    tag1: "CS Students",
    tag2: "CS Society",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/agm-2024-poster.webp"
  },
  {
    id: 4,
    name: "Varsity Hackathon 2024",
    date: " April 20 2024 ",
    dateDetails: "20th April 2024",
    time: "8:00am - 6:30pm (GMT+8)",
    venue: "Dewan Pembangunan Siswa 1, USM",
    session: "2023/2024",
    description: "A completely redesigned international hackathon and a space for university students to gain new hackathon experience.",
    details: "Varsity Hackathon, or V HACK, is the annual flagship event of the USM Computer Science Society, currently held for the third consecutive year, after the success of the inaugural V HACK 2022 and later, V HACK 2023. V HACK is one of the biggest student-led hackathons in Malaysia, with participants from both local and international universities competing to present their innovative solutions to a panel of highly accredited judges from both the industry and academics. \nSince its introduction, V HACK has continued the tradition of fostering innovation, collaboration, and creativity within the student community. The hackathon serves as a platform for aspiring developers, designers, and enthusiasts among university students to come together, explore cutting-edge technologies, and transform their ideas into tangible projects. \nThis year, V HACK returns, aiming to exceed previous successes and set new benchmarks for student-led hackathons in Malaysia. Collaborating with the Securities Commission Malaysia (SC), V HACK 2024 aims to deliver an unparalleled experience for participants. We’re elevating the event with expanded workshops, renowned speakers, expert mentors, and increased prize pools to reward the best of the best. Following the precedent set by V HACK 2023, V HACK 2024 will conduct its preliminary rounds online, culminating in a prestigious Grand Final hosted at Penang, Malaysia, where the top-performing teams will compete physically. \nLearn more about VHACK 2024 at our official website!",
    tag1: "International",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/vhack-2024-poster.webp"
  },
  {
    id: 5,
    name: "Sukan Antara Pusat Pengajian Sains 2024",
    date: " April 9 2024 ",
    dateDetails: "8th & 9th April 2024",
    time: "8:00am - 5:00pm (GMT+8)",
    venue: "Azman Hashim USM Sports Arena",
    session: "2023/2024",
    description: "A joint collaboration sports competition between seven competing Science Schools in USM.",
    details: "SUKAPPS, or also known as Sukan Antara Pusat Pengajian Sains is a sports competition between six competing Science Schools in USM. \nSchools involved: \n   •  School of Computer Sciences \n   •  ⁠School of Chemical Sciences \n   •  School of Mathematical Sciences \n   •  ⁠School of Biological Sciences \n   •  ⁠School of Pharmaceutical Sciences \n   •  ⁠School of Physics \n There were a variety of sports that each School was competing, including Futsal (M), Badminton (M & W), Volleyball (M & W), Netball (W). \nEach year, SUKAPPS will be hosted by one of the Science Schools in rotatiom, and this year it was hosted by School of Physics. \nWe are proud to announce that the School of Computer Sciences managed to rake in the Champion title for all Badminton categories (Men’s Single, Women’s Single, Men’s Double, Women’s Double, Mixed) and Third Place for Men’s Volleyball this year.",
    tag1: "Science Schools",
    tag2: "Sports",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/sukapps-2024-poster.webp"
  },
  {
    id: 6,
    name: "Frosty Fantasy Night 2023",
    date: " April 4 2024 ",
    dateDetails: "4th April 2024",
    time: "8:30pm - 11:30pm (GMT+8)",
    venue: "DK G31, School of Computer Sciences, USM",
    session: "2023/2024",
    description: "A brand new event specifically designed for computer science undergraduates to unwind and relax.",
    details: "A brand new event specifically designed for computer science undergraduates to unwind and relax. \nFrosty Fantasy Night 2024 aims to provide a break from the rigorous academic and coding schedules that students typically face. It features a variety of activities such as performance, lucky draw session and movie night, all intended to foster a sense of community among the participants. \nThis event encourages students to take a step back from their studies, engage in fun and stress-free activities, and connect with their peers in a relaxed environment. It’s a chance to build lasting connections and recharge your energy. \n",
    tag1: "CS Students",
    tag2: "Entertainment",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/frostynight-2023-poster.webp"
  },
  {
    id: 7,
    name: "Major Minor Exploration Event 2024",
    date: " Mar 5 2024 ",
    dateDetails: "4th & 5th March 2024",
    time: "8:00pm - 10:30pm (GMT+8)",
    venue: "Online",
    session: "2023/2024",
    description: "A 2-day virtual event aimed at helping first-year USM CS students to select their academic tracks.",
    details: "Major Minor Exploration Event 2024 is an online sharing session involving first-year and second-year students from the School of Computer Sciences, Universiti Sains Malaysia, as well as students from other schools who are interested in pursuing a minor in Computer Science. \nThe main objective of this sharing session is to provide detailed explanations and information about the process of selecting majors and minors for Bachelor of Computer Science (Honours) to assist students in choosing their minor in the second semester of their first year and their major in the second semester of their second year. Additionally, this sharing session also offers an opportunity for students from other schools to understand the minor courses offered by the School of Computer Sciences. \nME² 2024’s target group consists of first-year students from the School of Computer Sciences, Universiti Sains Malaysia, while the secondary target includes second-year students from the School of Computer Sciences, Universiti Sains Malaysia, and students from other schools who are interested in taking minor courses in Computer Science.",
    tag1: "Year 1",
    tag2: "Talk",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/me2-2024-poster.webp"
  },
  {
    id: 8,
    name: "Virtual Computer Science Internship & Recruitment Fair 2023",
    date: " Dec 4 2023 ",
    dateDetails: "4th December 2023",
    time: "8:45am - 4:30pm (GMT+8)",
    venue: "Online",
    session: "2023/2024",
    description: "A 1-day online event featuring career talks and sharing sessions primarily for computer science students at USM.",
    details: "Virtual Computer Science Internship & Recruitment Fair (VCSIRF) is an annual career fair organised by the USM Computer Science Society to provide industrial training placement opportunities for the third-year students and to supply employment opportunities for the final year students of the School of Computer Sciences, Universiti Sains Malaysia.\n This event is held virtually this year, enabling students to explore opportunities conveniently and gain valuable insights into their future careers. The event signifies the dedication of both the organisers and participating companies to support students in their journey towards successful and fulfilling careers in the field of computer science. \n Learn more about VCSIRF 2023 at our official website!",
    tag1: "Year 3 & 4",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/vcsirf-2023-poster.webp"
  },
  {
    id: 9,
    name: "CS Bersamamu 2023",
    date: " Oct 22 2023 ",
    dateDetails: "22nd October 2023",
    time: "9:30pm - 5:30pm (GMT+8)",
    session: "2023/2024",
    venue: "DK G31, School of Computer Sciences, USM",
    description: "An annual event that is organized to welcome and guide first-year students from School of Computer Sciences, USM.",
    details: "CS Bersamamu is an annual event that is organized by the senior committees from CS Society for the first-year students from School of Computer Sciences, USM. This program aims to prepare the first-year students for university life and establish a platform for them to get to know their course mates, lecturers, and the whole CS community. \nThis year, a series of engaging events took place, such as senior sharing session, booth exhibitions, recreational activities, and a hackathon session, all aimed at fostering camaraderie and facilitating a smooth transition into university life.",
    tag1: "Year 1",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2023-2024/csbersamamu-2023-poster.webp"
  },


  {
    id: 10,
    name: "Log Off Night 2023",
    date: " July 14 2023 ",
    dateDetails: "14th July 2023",
    time: "7:00pm - 11:00pm (GMT+8)",
    venue: "AC Hotel by Marriott Penang",
    session: "2022/2023",
    description: "An annual dinner to celebrate and appreciate final year computer science students' contributions.",
    details: "Log Off Night is an event to commemorate the end of the 2022/2023 academic year for all Computer Science students and holds immense significance for our final-year students, celebrating their accomplishments and bidding them farewell on their paths towards greater heights.",
    tag1: "USM Students",
    tag2: " Prom Night ",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/lon-2023-poster.webp"
  },

  {
    id: 11,
    name: "Project Innovation & eXploration in CS Education and Learning 2023",
    date: " July 12 2023 ",
    dateDetails: "7th June & 12th July 2023",
    time: "10:00am - 12:40pm (GMT+8)",
    venue: "Dewan Pembangunan Siswa 1, USM",
    session: "2022/2023",
    description: "An annual flagship exhibition programme specially curated for final year computer science students.",
    details: "Project Innovation & eXploration in CS Education and Learning (PIXEL 2023) is an annual flagship programme specially curated for final year students organised by the Computer Science Society in collaboration with the School of Computer Sciences, Universiti Sains Malaysia. PIXEL 2023 is an extension of the Final Year Projects (FYP) evaluation, allowing students to exhibit their projects and receive valuable feedback from industry professionals. \nThis year, PIXEL is back with more interesting awards and grand prizes, with the goal of reaching more important milestones and achievements. PIXEL 2023 will be held in a hybrid way. The exhibition and project evaluation will be held online while the Awards & Closing Ceremony will be held in person. Additionally, we will host CS PIXEL Day, a physical event initiative designed to raise awareness of FYP among students of other years, provide a subsidiary platform for senior-year students to exhibit their projects, and increase exposure to PIXEL 2023. \nCS PIXEL Day, which takes place on the 7th of June, offers an array of exciting activities including a physical project showcase, sponsor company booths, sharing sessions, engaging game booths and more! Additionally, a virtual project exhibition will be accessible through the PIXEL website, allowing the public to explore innovative projects by USM students online. To culminate the event, the Awards & Closing Ceremony will be held on the 12nd July 2023 at Dewan Pembangunan Siswa 1, Universiti Sains Malaysia where outstanding achievements will be recognized and celebrated. \nLearn more about PIXEL 2023 at our official website!",
    tag1: " Year 4 ",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/pixel-2023-poster.webp"
  },

  {
    id: 12,
    name: "Annual General Meeting 2023",
    date: " June 21 2023 ",
    dateDetails: "21st June 2023",
    time: "8:00pm - 11:00pm (GMT+8)",
    venue: "Online",
    session: "2022/2023",
    description: "An annual event to showcase the achievements of CS Society throughout the year and elect the new executives members.",
    details: "The Annual General Meeting (AGM) is an annual event of CS Society aimed to showcase the achievements of the CS Society throughout the academic year and election is done to elect the new Executive Members for the next academic session. \nThe annual activity report showcases the events that CS Society has organised throughout the academic session. Get a glimpse of the behind-the-scenes action, the dedication and the hard work put in by the committees. \nThe CS Society Board Election is your chance to make your voice heard and vote for the new Top Committee members of CS Society, who will shoulder the responsibilities of leading the student body toward greater heights.",
    tag1: " CS Students ",
    tag2: " CS Society ",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/agm-2023-poster.webp"
  },

  {
    id: 13,
    name: "CS Sports Day 2023",
    date: " Apr 30 2023 ",
    dateDetails: "30th April 2023",
    time: "8:00am - 7:00pm (GMT+8)",
    venue: "Azman Hashim USM Sports Arena",
    session: "2022/2023",
    description: "A brand-new student-led sports event for students and lecturers in the School of Computer Sciences.",
    details: "CS Sports Day 2023 is a student-led sports event aims to foster camaraderie and team spirit among the students and lecturers in the School of Computer Sciences. This event is a great opportunity for sports enthusiasts to showcase your athletic skills and team spirit. Three categories are available: Men’s Futsal, Men’s Double Badminton, and Women’s Double Badminton.",
    tag1: "CS Students",
    tag2: "Sports",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/cs-sports-day-2023-poster.webp"
  },

  {
    id: 14,
    name: "Varsity Hackathon 2023",
    date: " Apr 2 2023 ",
    dateDetails: "2nd April 2023",
    time: "9:00am - 6:30pm (GMT+8)",
    venue: "Dewan Utama Pelajar, USM",
    session: "2022/2023",
    description: "A completely redesigned international hackathon and a space for university students to gain new hackathon experience.",
    details: "Varsity Hackathon (V Hack), is a year-old flagship program, initiated in the early months of 2022. V Hack is one of the largest student-led international intervarsity competition for local and international undergraduates to compete by formulating the best solutions to solve real-world issues. \nV Hack aims to break the norms and expose our Malaysian undergraduates of all disciplines to the wonders of hackathons. It provides the participants a platform to gain new experiences and widen their exposure in various issues as an undergraduate. Furthermore, V Hack is the place for them to enhance their technical skills with professionals around the globe, develop ground-breaking ideas alongside expanding their network with likeminded people. \nLearn more about us at our official website!",
    tag1: "International",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/vhack-2023-poster.webp"
  },
  {
    id: 15,
    name: "Major Minor Exploration Event 2023",
    date: " Mar 5 2023 ",
    dateDetails: "4th & 5th March 2023",
    time: "8:00pm - 10:00pm (GMT+8)",
    venue: "Online",
    session: "2022/2023",
    description: "A virtual event aimed at helping first-year USM CS students to select their academic tracks.",
    details: "Major Minor Exploration Event 2023 (ME² 2023) is a virtual sharing session specially organised for 1st Year students from the School of Computer Sciences at the Universiti Sains Malaysia. The two-day event aims to provide a clearer insight on the majors, minors, and electives programmes for the Bachelor of Computer Science course and help students make informed decisions about their academic journey in the field of Computer Science. During the event, senior students will share their experiences and insights into the various programs and highlight the unique features, benefits, and career paths associated with each one. By the end of the sharing session, students will gain a better understanding of the courses and select the most suitable track for them by Year 1 Semester 2.",
    tag1: "Year 1",
    tag2: "Talk",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/me2-2023-poster.webp"
  },
  {
    id: 16,
    name: "C++ Clinic 2023",
    date: " Jan 28 2023 ",
    dateDetails: "27th & 28th January 2023",
    time: "8:00pm - 10:30pm (GMT+8)",
    venue: "Online",
    session: "2022/2023",
    description: "An online C++ coding workshop involving first-year computer science students from USM in preparation for their final exam.",
    details: "An online C++ coding workshop involving first-year computer science students from Universiti Sains Malaysia (USM). Through this workshop, the students’ programming skills can be sharpened to further empower their technical skills and understanding in preparation for their final exam.",
    tag1: "Year 1",
    tag2: "Workshop",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/cpp-clinic-2023-poster.webp"
  },
  {
    id: 17,
    name: "Computer Science Internship & Recruitment Fair 2022",
    date: " Jan 7 2023 ",
    dateDetails: "7th January 2023",
    time: "9:00am - 6:00pm (GMT+8)",
    venue: "Dewan Utama Pelajar, USM",
    session: "2022/2023",
    description: "A 2-day physical event featuring career talks and exhibitions uniquely for computer science students at USM.",
    details: "Computer Science Internship and Recruitment Fair (CSIRF) 2022 is a 2-day event featuring career talks and exhibitions for undergraduate students at USM. This annual event has been successful in securing internships and employment offers for students in the past. \nThis year, the event will be conducted in-person on the USM campus, providing students with an opportunity to learn about potential internship and job opportunities from participating companies. CS Society will develop a custom website for job postings and applications. \nCSIRF 2022 is open to all USM Computer Science students who are interested in joining the career talks and exhibitions. It is a valuable opportunity for participating companies to promote themselves to a wider audience of potential recruits, and for students to gain insights and connections that can help them launch their careers in the tech industry.",
    tag1: "Year 3 & 4",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/csirf-2022-poster.webp"
  },
  {
    id: 18,
    name: "CS Bersamamu 2022",
    date: " Oct 29 2022 ",
    dateDetails: "29th October 2022",
    time: "8:00pm - 11:10pm (GMT+8)",
    venue: "Online",
    session: "2022/2023",
    description: "An annual event that is organized for the first-year students from School of Computer Sciences, USM.",
    details: "CS Bersamamu is an annual event that is organized by the senior committees from CS Society for the first-year students from School of Computer Sciences, USM. This program aims to prepare the first-year students for university life and establish a platform for them to get to know their course mates, lecturers, and the whole CS community. \nActivities including the ice-breaking session, station games and sharing session are included to strengthen their bond to ease their first step into university. \nStay tuned on event updates on this page and in our social media!",
    tag1: "Year 1",
    tag2: "Flagship",
    img: "https://cssocietyusm.com/assets/img/events/2022-2023/csbersamamu-2022-poster.webp"
  },
  {
    id: 19,
    name: "Testing Event 2022",
    date: " Oct 28 2022 ",
    dateDetails: "28th Oct 2022",
    time: "10:00am - 12:40pm (GMT+8)",
    venue: "Online",
    session: "2022/2023",
    description: "Testing testing 123",
    details: "Lorem ipsum odor amet, consectetuer adipiscing elit. Nostra curae habitant sit, amet ultrices duis. Ex torquent netus donec dignissim nibh lectus feugiat vel. Interdum dis vehicula per iaculis ad taciti sapien dolor. Morbi est venenatis nisl accumsan vehicula. Sed tellus eu curae varius inceptos pharetra. Libero penatibus magnis orci maecenas sociosqu penatibus porta. \nPlatea gravida commodo curabitur risus rhoncus arcu. Euismod ad inceptos dictum hac in proin mus feugiat. Egestas libero cubilia; sollicitudin ridiculus aliquam ultricies. Pellentesque ad auctor ultricies, molestie pulvinar dignissim. Sem nunc tempor magna semper ante magna duis accumsan integer. Non facilisi velit ridiculus inceptos elit sociosqu. Fames molestie erat tempus metus id ultrices sociosqu. In praesent aptent amet enim malesuada semper velit. Mus accumsan donec est rhoncus ut convallis et class lacinia.",
    tag1: "Year 1",
    tag2: "Flagship",
    img: "https://picsum.photos/200"
  },
  {
    id: 20,
    name: "Testing Event 2022",
    date: " April 28 2022 ",
    dateDetails: "28th April 2022",
    time: "10:00am - 12:40pm (GMT+8)",
    venue: "Dewan Budaya, USM",
    session: "2021/2022",
    description: "Testing testing 123",
    details: "Lorem ipsum odor amet, consectetuer adipiscing elit. Nostra curae habitant sit, amet ultrices duis. Ex torquent netus donec dignissim nibh lectus feugiat vel. Interdum dis vehicula per iaculis ad taciti sapien dolor. Morbi est venenatis nisl accumsan vehicula. Sed tellus eu curae varius inceptos pharetra. Libero penatibus magnis orci maecenas sociosqu penatibus porta. \nPlatea gravida commodo curabitur risus rhoncus arcu. Euismod ad inceptos dictum hac in proin mus feugiat. Egestas libero cubilia; sollicitudin ridiculus aliquam ultricies. Pellentesque ad auctor ultricies, molestie pulvinar dignissim. Sem nunc tempor magna semper ante magna duis accumsan integer. Non facilisi velit ridiculus inceptos elit sociosqu. Fames molestie erat tempus metus id ultrices sociosqu. In praesent aptent amet enim malesuada semper velit. Mus accumsan donec est rhoncus ut convallis et class lacinia.",
    tag1: "Year 1",
    tag2: "Flagship",
    img: "https://picsum.photos/200"
  },
];

export default events;